eureka:
  instance :
    prefer-ip-address: true  # Register with IP instead of hostname
    hostname: localhost  # Explicitly set the hostname
  client:
    fetch-registry : true
    register-with-eureka : true
    service-url :
      defaultZone : http://localhost:8761/eureka
